### ISSUE TITLE
Upload ova file to github release assets via script

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara-quickstart#23]
> https://gist.github.com/stefanbuck/ce788fee19ab6eb0b4447a85fc99f447

It would be great if we can upload image from Jenkins job too.

**Comment by vitojeng** [comment]
@jackyoh Can we enable this function when we release v0.10.0 ?

**Comment by jackyoh** [comment]
有可能可以，我再來研究看看。

**Comment by jackyoh** [comment]
目前有測試使用 GitHub 的 api 將檔案 upload 到 GitHub 的 repo 上，指令如下：

```
curl -X POST 'https://api.github.com/repos/owner/${REPO}/releases/${RELEASE_NAME}/assets?access_token=${TOKEN}&name=${FILE_NAME}' --header 'Content-Type: application/zip' --upload-file ${LOCAL_FILE_PATH_AND_NAME}
```

GITHUB 的 TOKEN 建立方式：
Settings -> Developer settings -> Personal access tokens -> Generate new token

之後會將以上的指令整合到 QA 的 QuicklyStartVM 的 job 裡，之後在 build 完 Quickly Start VM 之後就會將檔案上傳到 GitHub 的 release 畫面上。

**Comment by vitojeng** [comment]
酷~ 感謝 @jackyoh !
jenkins job name `BuildOharaQuicklyStartVM` 可否改成這個 `DeployQuickstartVM` ?

**Comment by jackyoh** [comment]
OK, 我來修改。

**Comment by chia7712** [comment]
請問一下是指什麼檔案? ISO檔嗎?

**Comment by jackyoh** [comment]
使用 build 完 quickly start VM 之後是 *.ova 檔，目前我的測試是把檔案打包成 zip 檔之後, 透過 GitHub api 將 quickly start VM 的檔案上傳。

**Comment by chia7712** [comment]
> 使用 build 完 quickly start VM 之後是 *.ova 檔

不會撞到檔案大小的限制嗎? 我記得好像是2GB?

**Comment by vitojeng** [comment]
我沒有把 docker image 包進 VM, 是在 VM 第一次 login 時, 自動 pull images.
因此 image 檔案不會超過 2GB, 因此上傳只需要一個即可. 這樣也不用 docker image 有變動, ova 就要重 build 一次.

**Comment by vitojeng** [comment]
> 使用 build 完 quickly start VM 之後是 *.ova 檔，目前我的測試是把檔案打包成 zip 檔之後, 透過 GitHub api 將 quickly start VM 的檔案上傳。

@jackyoh 我們是直接傳 ova 檔案喔, 不要再做 zip 壓縮

**Comment by jackyoh** [comment]
OK, 我會在做測試。

**Comment by jackyoh** [comment]
以下是上傳檔案到 github release 的 shell script，因為 upload file 的 API 需要傳入 Release ID 因此需要使用 tags 的 API 找到 release ID 才能做 file upload 的動作。 

```
#!/bin/bash
tagName="0.10.0"

releaseID=$(curl -s -X GET -u "$userName:$password" https://api.github.com/repos/$own/$repo/releases| jq -r --arg tagName "$tagName" '[.[] | select(.tag_name==$tagName)][0] | .id')
echo $releaseID

uploadFilepath="/home/user1/"
uploadFilename="ohara-quickstart-0.9.0.ova"
uploadUrl="https://uploads.github.com/repos/jackyoh/ohara-connector-demo/releases/$releaseID/assets"

curl -s -u "$userName:$password" \
        -H "Content-Type: application/zip" \
        -X POST \
        --data-binary @$uploadFilepath/$uploadFilename  \
        "$uploadUrl?name=$uploadFilename"
```

**Comment by jackyoh** [comment]
目前已經可以使用 QA 將 build 好或是現有 quickly start 的 ova file 上傳到 github 上了。我先把此議題關閉，如果有發現問題在開 issue 給我。
