### ISSUE TITLE
Add a script to cleanup ohara images

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara-quickstart#49]
For example
```bash
# cleanup-images.sh
docker rm -f $(docker ps -aq)
docker rmi $(docker images -q)
reboot
```

**Comment by vitojeng** [comment]
@jackyoh Can you take this job?

**Comment by jackyoh** [comment]
OK, 這個議題我來實作。

我先確認一下，執行以上 script 的時機，是使用者下  ./cleanup-images.sh 的指令才執行還是有其它的時間點。

**Comment by vitojeng** [comment]
這個算是協助的 script, 所以只有 user 需要 clean 時才會執行~

**Comment by vitojeng** [comment]
因為在啟動時, 若是 image 不存在自動下載.
所以使用者可以執行這個 script 做清除, 達到更新 ohara image 的目的.

**Comment by jackyoh** [comment]
> 因為在啟動時, 若是 image 不存在自動下載.

了解。所以 cleanup-images.sh 主要的目的是用來重啟 vm 時，順便更新 docker images。那這樣要順便做 update 的 script 嗎？因為這樣就不用重啟 vm 了

**Comment by vitojeng** [comment]
> > 因為在啟動時, 若是 image 不存在自動下載.
> 
> 了解。所以 cleanup-images.sh 主要的目的是用來重啟 vm 時，順便更新 docker images。

不是。cleanup-images.sh 的目的只有清除 image 而已。

> 那這樣要順便做 update 的 script 嗎？因為這樣就不用重啟 vm 了

vm 重啟不是太問題，也很快。所以我想不用做。

**Comment by jackyoh** [comment]
OK, 了解。我來先做 cleanup-images.sh 的部份，如果 update 的部份在實作時沒卡到我就把它做掉

**Comment by vitojeng** [comment]
感謝 ~ 🙏
