### ISSUE TITLE
Create a VM to build quickstart VM

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara-quickstart#5]
follow-up oharastream/ohara#2440

- [x] Create a VirtualBox VM to build quickstart VM
- [x] Integrate with Jenkins job

**Comment by vitojeng** [comment]
Thanks @jackyoh for jenkins integration support.

**Comment by jackyoh** [comment]
目前已經把 build quickstart VM 整到 jenkins 的 job 了, Job Name 為 OharaQuicklyStartVM

**Comment by vitojeng** [comment]
done!
