### ISSUE TITLE
Unable to create a workspace

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara-quickstart#62]
### Not able to create a workspace

While creating a new workspace through our UI with the v0.12.0 snapshot images, the following error occurred: 

> "code":"java.lang.IllegalArgumentException"
"message":"192.168.56.122 does not have image:oharastream/zookeeper:0.13.0-SNAPSHOT. It has images:oharastream/manager:0.12.0,oharastream/connect-worker:0.12.0,oharastream/shabondi:0.12.0,oharastream/broker:0.12.0,oharastream/configurator:0.12.0,oharastream/stream:0.12.0,oharastream/zookeeper:0.12.0"
"stack":"java.lang.IllegalArgumentException: 192.168.56.122 does not have image:oharastream/zookeeper:0.13.0-SNAPSHOT. It has images:oharastream/manager:0.12.0,oharastream/connect-worker:0.12.0,oharastream/shabondi:0.12.0,oharastream/broker:0.12.0,oharastream/configurator:0.12.0,oharastream/stream:0.12.0,oharastream/zookeeper:0.12.0 at oharastream.ohara.configurator.route.package$.$anonfun$checkResourcesConflict$4(package.scala:308) at oharastream.ohara.configurator.route.package$.$anonfun$checkResourcesConflict$4$adapted(package.scala:304) at scala.collection.immutable.Set$Set1.foreach(Set.scala:168) at oharastream.ohara.configurator.route.package$.$anonfun$checkResourcesConflict$3(package.scala:304) at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:430) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.lang.Thread.run(Thread.java:834) "

### Screenshots:
![S0 image](https://i.imgur.com/sT0aRBe.png)

![S1 image](https://i.imgur.com/AQsK2tD.png)

**Comment by konekoya** [comment]
@jackyoh could you have a look at this issue? 🙏

**Comment by jackyoh** [comment]
OK, 我來看看。

**Comment by konekoya** [comment]
謝傑克

**Comment by konekoya** [comment]
@jackyoh Tested with the new images, works perfectly. Thanks!
